def tree(x,y,z,p):
    if p == 0:
        voxel = Voxel(position = (x, y+1, z), texture = wood_texture)

        voxel = Voxel(position = (x, y+2, z), texture = wood_texture)

        voxel = Voxel(position = (x, y+3, z), texture = wood_texture)
        voxel = Voxel(position = (x+1, y+3, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+3, z), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+3, z), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+3, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+3, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+3, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+3, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+3, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x, y+3, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+3, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+3, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x, y+3, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+3, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+3, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+3, z), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+3, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+3, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+3, z), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+3, z+1), texture = leaves_texture)

        voxel = Voxel(position = (x, y+4, z), texture = wood_texture)
        voxel = Voxel(position = (x+1, y+4, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+4, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+4, z), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+4, z), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+4, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+4, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+4, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+4, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+4, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x, y+4, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+4, z-2), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+4, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x, y+4, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+4, z+2), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+4, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+4, z), texture = leaves_texture)
        voxel = Voxel(position = (x+2, y+4, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+4, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+4, z), texture = leaves_texture)
        voxel = Voxel(position = (x-2, y+4, z+1), texture = leaves_texture)

        voxel = Voxel(position = (x, y+5, z), texture = wood_texture)
        voxel = Voxel(position = (x+1, y+5, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+5, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+5, z), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+5, z), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+5, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+5, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+5, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+5, z-1), texture = leaves_texture)

        voxel = Voxel(position = (x, y+6, z), texture = leaves_texture)
        voxel = Voxel(position = (x, y+6, z-1), texture = leaves_texture)
        voxel = Voxel(position = (x, y+6, z+1), texture = leaves_texture)
        voxel = Voxel(position = (x-1, y+6, z), texture = leaves_texture)
        voxel = Voxel(position = (x+1, y+6, z), texture = leaves_texture)
        
    else:
        voxel = Voxel(position = (x, y+1, z), texture = wood_texture)
                        
        voxel = Voxel(position = (x, y+2, z), texture = wood_texture)

        for i in range(3,5):
            voxel = Voxel(position = (x, y+i, z), texture = wood_texture)
            voxel = Voxel(position = (x+1, y+i, z+1), texture = leaves_texture)
            voxel = Voxel(position = (x-1, y+i, z+1), texture = leaves_texture)
            voxel = Voxel(position = (x+1, y+i, z), texture = leaves_texture)
            voxel = Voxel(position = (x-1, y+i, z), texture = leaves_texture)
            voxel = Voxel(position = (x+1, y+i, z-1), texture = leaves_texture)
            voxel = Voxel(position = (x-1, y+i, z-1), texture = leaves_texture)
            voxel = Voxel(position = (x, y+i, z+1), texture = leaves_texture)
            voxel = Voxel(position = (x, y+i, z-1), texture = leaves_texture)
    
